/**
 * Generated by anjay_codegen.py on 2020-05-26 16:26:20
 *
 * LwM2M Object: Temperature
 * ID: 3303, URN: urn:oma:lwm2m:ext:3303, Optional, Multiple
 *
 * This IPSO object should be used with a temperature sensor to report a
 * temperature measurement.  It also provides resources for
 * minimum/maximum measured values and the minimum/maximum range that can
 * be measured by the temperature sensor. An example measurement unit is
 * degrees Celsius.
 */
#include <assert.h>
#include <stdbool.h>

#include <anjay/anjay.h>
#include <avsystem/commons/avs_defs.h>
#include <avsystem/commons/avs_list.h>
#include <avsystem/commons/avs_memory.h>

#include "avst_utils.h"

/**
 * Min Measured Value: R, Single, Optional
 * type: float, range: N/A, unit: N/A
 * The minimum value measured by the sensor since power ON or reset.
 */
#define RID_MIN_MEASURED_VALUE 5601

/**
 * Max Measured Value: R, Single, Optional
 * type: float, range: N/A, unit: N/A
 * The maximum value measured by the sensor since power ON or reset.
 */
#define RID_MAX_MEASURED_VALUE 5602

/**
 * Min Range Value: R, Single, Optional
 * type: float, range: N/A, unit: N/A
 * The minimum value that can be measured by the sensor.
 */
#define RID_MIN_RANGE_VALUE 5603

/**
 * Max Range Value: R, Single, Optional
 * type: float, range: N/A, unit: N/A
 * The maximum value that can be measured by the sensor.
 */
#define RID_MAX_RANGE_VALUE 5604

/**
 * Reset Min and Max Measured Values: E, Single, Optional
 * type: N/A, range: N/A, unit: N/A
 * Reset the Min and Max Measured Values to Current Value.
 */
#define RID_RESET_MIN_AND_MAX_MEASURED_VALUES 5605

/**
 * Sensor Value: R, Single, Mandatory
 * type: float, range: N/A, unit: N/A
 * Last or Current Measured Value from the Sensor.
 */
#define RID_SENSOR_VALUE 5700

/**
 * Sensor Units: R, Single, Optional
 * type: string, range: N/A, unit: N/A
 * Measurement Units Definition.
 */
#define RID_SENSOR_UNITS 5701

typedef struct temperature_instance_struct {
    anjay_iid_t iid;

    // TODO: instance state
    bool has_sensor_units;
    char* sensor_units;

    bool has_sensor_value;
    float sensor_value;

    float last_notify_sensor_value;
} temperature_instance_t;

typedef struct temperature_object_struct {
    const anjay_dm_object_def_t *def;
    AVS_LIST(temperature_instance_t) instances;

    // TODO: object state
} temperature_object_t;

static inline temperature_object_t *
get_obj(const anjay_dm_object_def_t *const *obj_ptr) {
    assert(obj_ptr);
    return AVS_CONTAINER_OF(obj_ptr, temperature_object_t, def);
}

static temperature_instance_t *find_instance(const temperature_object_t *obj,
                                             anjay_iid_t iid) {
    AVS_LIST(temperature_instance_t) it;
    AVS_LIST_FOREACH(it, obj->instances) {
        if (it->iid == iid) {
            return it;
        } else if (it->iid > iid) {
            break;
        }
    }

    return NULL;
}

static int list_instances(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_dm_list_ctx_t *ctx) {
    (void) anjay;

    AVS_LIST(temperature_instance_t) it;
    AVS_LIST_FOREACH(it, get_obj(obj_ptr)->instances) {
        anjay_dm_emit(ctx, it->iid);
    }

    return 0;
}

static int init_instance(temperature_instance_t *inst, anjay_iid_t iid) {
    assert(iid != ANJAY_ID_INVALID);

    inst->iid = iid;
    // TODO: instance init
    inst->sensor_value = 0.0;
    inst->sensor_units = "C";
    // TODO: return 0 on success, negative value on failure
    return 0;
}

static void release_instance(temperature_instance_t *inst) {
    // TODO: instance cleanup
    (void) inst;
}

static temperature_instance_t *
add_instance(temperature_object_t *obj, anjay_iid_t iid) {
    assert(find_instance(obj, iid) == NULL);

    AVS_LIST(temperature_instance_t) created =
            AVS_LIST_NEW_ELEMENT(temperature_instance_t);
    if (!created) {
        return NULL;
    }

    int result = init_instance(created, iid);
    if (result) {
        AVS_LIST_CLEAR(&created);
        return NULL;
    }

    AVS_LIST(temperature_instance_t) *ptr;
    AVS_LIST_FOREACH_PTR(ptr, &obj->instances) {
        if ((*ptr)->iid > created->iid) {
            break;
        }
    }

    AVS_LIST_INSERT(ptr, created);
    return created;
}

static int instance_create(anjay_t *anjay,
                           const anjay_dm_object_def_t *const *obj_ptr,
                           anjay_iid_t iid) {
    (void) anjay;
    temperature_object_t *obj = get_obj(obj_ptr);
    assert(obj);

    return add_instance(obj, iid) ? 0 : ANJAY_ERR_INTERNAL;
}

static int instance_remove(anjay_t *anjay,
                           const anjay_dm_object_def_t *const *obj_ptr,
                           anjay_iid_t iid) {
    (void) anjay;
    temperature_object_t *obj = get_obj(obj_ptr);
    assert(obj);

    AVS_LIST(temperature_instance_t) *it;
    AVS_LIST_FOREACH_PTR(it, &obj->instances) {
        if ((*it)->iid == iid) {
            release_instance(*it);
            AVS_LIST_DELETE(it);
            return 0;
        } else if ((*it)->iid > iid) {
            break;
        }
    }

    assert(0);
    return ANJAY_ERR_NOT_FOUND;
}

static int instance_reset(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_iid_t iid) {
    (void) anjay;

    temperature_object_t *obj = get_obj(obj_ptr);
    assert(obj);
    temperature_instance_t *inst = find_instance(obj, iid);
    assert(inst);

    inst->sensor_value = 0.0;
    return 0;
}

static int list_resources(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_iid_t iid,
                          anjay_dm_resource_list_ctx_t *ctx) {
    (void) anjay;
    (void) obj_ptr;
    (void) iid;

   /* anjay_dm_emit_res(ctx, RID_MIN_MEASURED_VALUE,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_MAX_MEASURED_VALUE,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_MIN_RANGE_VALUE,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_MAX_RANGE_VALUE,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_RESET_MIN_AND_MAX_MEASURED_VALUES,
                      ANJAY_DM_RES_E, ANJAY_DM_RES_PRESENT);*/
    anjay_dm_emit_res(ctx, RID_SENSOR_VALUE,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_SENSOR_UNITS,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    return 0;
}

static int resource_read(anjay_t *anjay,
                         const anjay_dm_object_def_t *const *obj_ptr,
                         anjay_iid_t iid,
                         anjay_rid_t rid,
                         anjay_riid_t riid,
                         anjay_output_ctx_t *ctx) {
    (void) anjay;

    temperature_object_t *obj = get_obj(obj_ptr);
    assert(obj);
    temperature_instance_t *inst = find_instance(obj, iid);
    assert(inst);

    switch (rid) {
    case RID_SENSOR_VALUE:
        assert(riid == ANJAY_ID_INVALID);
        float current_sensor_value;

        avst_get_cpu_temperature(&current_sensor_value);

        return anjay_ret_float(ctx, current_sensor_value); // TODO

    case RID_SENSOR_UNITS:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_string(ctx, inst->sensor_units); // TODO
    default:
        return ANJAY_ERR_METHOD_NOT_ALLOWED;
    }
}

static int resource_execute(anjay_t *anjay,
                            const anjay_dm_object_def_t *const *obj_ptr,
                            anjay_iid_t iid,
                            anjay_rid_t rid,
                            anjay_execute_ctx_t *arg_ctx) {
    (void) arg_ctx;

    temperature_object_t *obj = get_obj(obj_ptr);
    assert(obj);
    temperature_instance_t *inst = find_instance(obj, iid);
    assert(inst);

    switch (rid) {
    /*case RID_RESET_MIN_AND_MAX_MEASURED_VALUES:
        return ANJAY_ERR_NOT_IMPLEMENTED; // TODO
*/
    default:
        return ANJAY_ERR_METHOD_NOT_ALLOWED;
    }
}

static const anjay_dm_object_def_t OBJ_DEF = {
    .oid = 3303,
    .handlers = {
        .list_instances = list_instances,
        .instance_create = instance_create,
        .instance_remove = instance_remove,
        .instance_reset = instance_reset,

        .list_resources = list_resources,
        .resource_read = resource_read,
        .resource_execute = resource_execute,

        // TODO: implement these if transactional write/create is required
        .transaction_begin = anjay_dm_transaction_NOOP,
        .transaction_validate = anjay_dm_transaction_NOOP,
        .transaction_commit = anjay_dm_transaction_NOOP,
        .transaction_rollback = anjay_dm_transaction_NOOP
    }
};

const anjay_dm_object_def_t **temperature_object_create(void) {
    temperature_object_t *obj = (temperature_object_t *) avs_calloc(1, sizeof(temperature_object_t));

    if (!obj) {
        return NULL;
    }
    obj->def = &OBJ_DEF;

    temperature_instance_t *inst = add_instance(obj, 0);
    if (inst) {
        inst->sensor_value = 0.0;
        inst->sensor_units = "C";
    } else {
        avs_free(obj);
        return NULL;
    }

    return &obj->def;
}


void temperature_object_release(const anjay_dm_object_def_t **def) {
    if (!def) {
        return;
    }
    temperature_object_t *repr = get_obj(def);
    AVS_LIST_CLEAR(&repr->instances);
    avs_free(repr);
}


void temperature_object_notify(anjay_t *anjay, const anjay_dm_object_def_t **def) {
    if (!anjay && !def) {
        return;
    }
    temperature_object_t *obj = get_obj(def);

    float current_sensor_value;
    if (avst_get_cpu_temperature(&current_sensor_value)) {
        return;
    }

    AVS_LIST(temperature_instance_t) it;
    AVS_LIST_FOREACH(it, obj->instances) {
        if (it->last_notify_sensor_value != current_sensor_value) {
            if (!anjay_notify_changed(anjay, 3303, it->iid, RID_SENSOR_VALUE)) {
                it->last_notify_sensor_value = current_sensor_value;
            }
        }
    }
}